apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: spr-ra-irest
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spr-ra-irest 
  name: spr-ra-irest
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: spr-ra-irest
    weight: 100 
