apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: spr-ra-irest
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spr-ra-irest 
  name: spr-ra-irest
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: spr-ra-irest 
